### ISSUE TITLE
underscores in inline code elements in headers don't work as expected

### ISSUE THREAD

**Issue by KimStebel** [yogthos/markdown-clj#88] opened 2015-12-30 17:09 UTC
```
## some header `with_an_underscore`
```

produces

```
<h2> some header <code>with&</h2>
```

instead of 

```
<h2> some header <code>with_an_underscore</code></h2>
```

**Comment by yogthos** [comment] 2015-12-30 17:52
Yup, that looks like a bug, I can reproduce locally. Probably won't have time to look at it in the next little while though. It looks like it's caused by escaping when the header is passed. As a workaround for now you could use the alternative heading declaration:

```
some header `with_an_underscore`
==
```

**Comment by KimStebel** [comment] 2015-12-30 18:06
Thanks for letting me know about the workaround. I had a brief look at the source to see whether I could figure out what's going wrong but it wasn't obvious.

**Comment by yogthos** [comment] 2015-12-30 18:20
good news, I think just fixed the issue, if you could confirm with `0.9.85` we can close it :)

**Comment by yogthos** [comment] 2015-12-30 18:21
Looks like the issue was in how I was parsing out the `#` tags in the header, I switched to using a regex and it's handling it more intelligently now.

**Comment by KimStebel** [comment] 2015-12-30 18:27
Cool, that works for me! Thanks!

**Comment by yogthos** [comment] 2015-12-30 18:37
:+1:

**Closed by yogthos** 2015-12-30 18:37 UTC
